[tool.ruff]
# Add the `line-too-long` rule to the enforced rule set. By default, Ruff omits rules that
# overlap with the use of a formatter, like Black, but we can override this behavior by
# explicitly adding the rule.
select = ["E4", "E7", "E9", "F"]
extend-select = ["E", "W"]
# Set the maximum line length to 79 characters.
line-length = 79

[tool.pyright]
reportUnboundVariable = false
typeCheckingMode = "off"
reportUnusedVariable = "off"
